name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v3.7.11
        with:
          include-v-in-tag: false
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases-created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v1.1.0
        with:
          node-version-file: .tool-versions
      - name: Build
        shell: sh
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: "./packages/page/build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.3
