name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          include-v-in-tag: false
      - name: Setup Pages
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/configure-pages@v2
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set node
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        if: ${{ steps.release.outputs.release_created }}
        shell: sh
        run: pnpm install --no-frozen-lockfile
      - name: Build with Next.js
        if: ${{ steps.release.outputs.release_created }}
        shell: sh
        run: pnpm run build
      - name: Static HTML export with Next.js
        if: ${{ steps.release.outputs.release_created }}
        shell: sh
        run: pnpm run export
      - name: Upload artifact
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - name: Deploy to GitHub Pages
        if: ${{ steps.release.outputs.release_created }}
        id: deployment
        uses: actions/deploy-pages@v2
